### ISSUE TITLE
0.5.1: cannot build module documentation

### ISSUE THREAD

**Issue by kloczek** [sphinx-toolbox/default_values#52]
## Description
Cannot build module documention on building rpm package process.
It fails because it cannot find `sphinxcontrib.extras_require`

-----
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>

## Steps to Reproduce
- build module `/usr/bin/python3 -sBm build -w --no-isolation`
- build documentation `sphinx-build -n -T -W -b man doc-source build/sphinx/man`
## Actual result:
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
* Building wheel...
Copying /home/tkloczko/rpmbuild/BUILD/default_values-0.5.1/sphinxcontrib/default_values/__init__.py -> sphinxcontrib/default_values/__init__.py
Copying /home/tkloczko/rpmbuild/BUILD/default_values-0.5.1/sphinxcontrib/default_values/demo.py -> sphinxcontrib/default_values/demo.py
Copying /home/tkloczko/rpmbuild/BUILD/default_values-0.5.1/sphinxcontrib/default_values/py.typed -> sphinxcontrib/default_values/py.typed
Writing default_values-0.5.1.dist-info/LICENSE
Writing default_values-0.5.1.dist-info/entry_points.txt
Writing default_values-0.5.1.dist-info/METADATA
Writing default_values-0.5.1.dist-info/WHEEL
Writing default_values-0.5.1.dist-info/top_level.txt
Writing default_values-0.5.1.dist-info/RECORD
Wheel created at /home/tkloczko/rpmbuild/BUILD/default_values-0.5.1/dist/default_values-0.5.1-py3-none-any.whl
Successfully built default_values-0.5.1-py3-none-any.whl
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/default_values-0.5.1
+ sphinx-build -n -T -W -b man doc-source build/sphinx/man
Running Sphinx v4.5.0
loading translations [en]... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.extras_require'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 428, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.extras_require (exception: No module named 'sphinxcontrib.extras_require')

Extension error:
Could not import extension sphinxcontrib.extras_require (exception: No module named 'sphinxcontrib.extras_require')
```
I've been trying to add $PYTHONPATH to env of the executed `sphinx-build` command but resuld is the same
```console
[tkloczko@devel-g2v default_values-0.5.1]$ PYTHONPATH=$PWD sphinx-build -n -T -W -b man doc-source build/sphinx/man
Running Sphinx v4.5.0
loading translations [en]... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.extras_require'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 428, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.extras_require (exception: No module named 'sphinxcontrib.extras_require')

Extension error:
Could not import extension sphinxcontrib.extras_require (exception: No module named 'sphinxcontrib.extras_require')
```console
I've tested as well execution of the sphinx-build after installation of the .whl archive in </install/prefix> so in thi scase are available modole metadata and sphinx-build fails as well
```consile
+ /usr/bin/python3 -sBm pip install -I dist/default_values-0.5.1-py3-none-any.whl --root /home/tkloczko/rpmbuild/BUILDROOT/python-default-values-0.5.1-2.fc35.x86_64 --disable-pip-version-check --no-cache-dir --no-deps --no-index --no-warn-script-location --progress-bar off --verbose --ignore-installed --no-warn-script-location
Using pip 22.0.4 from /usr/lib/python3.8/site-packages/pip (python 3.8)
Processing ./dist/default_values-0.5.1-py3-none-any.whl
Installing collected packages: default-values
Successfully installed default-values-0.5.1
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-default-values-0.5.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ sphinx-build -n -T -W -b man doc-source build/sphinx/man
Running Sphinx v4.5.0
loading translations [en]... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.extras_require'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 428, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.extras_require (exception: No module named 'sphinxcontrib.extras_require')
```
## Expected result:
It should be possible to build documentation without actually installed module to allow build it duringtypical packaging process.

## Reproduces how often:
Easily reproduced

## Version

  * Operating System: Linux x86/64
  * Python: 3.8.12
  * default_values: 0.5.1

## Installation source
Autogenerated by github from git tag tar ball https://github.com/sphinx-toolbox/default_values//archive/v0.5.1/python-default-values-0.5.1.tar.gz

**Comment by kloczek** [comment]
Gentle ping .. any update? 🤔 
Just tested 0.6.0 and sphinx still fails
```console
+ /usr/bin/sphinx-build -n -T -b man doc-source build/sphinx/man
Running Sphinx v8.1.3
loading translations [en]... done
making output directory... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
WARNING: Unable to determine documentation url for project docutils
WARNING: Unable to determine documentation url for project sphinx-jinja2-compat
[autosummary] generating autosummary for: 404.rst, Source.rst, demo.rst, docs.rst, images.rst, index.rst, license.rst, usage/configuration.rst, usage/installation.rst
loading intersphinx inventory 'python' from https://docs.python.org/3/objects.inv ...
loading intersphinx inventory 'sphinx' from https://www.sphinx-doc.org/en/stable/objects.inv ...
intersphinx inventory has moved: https://www.sphinx-doc.org/en/stable/objects.inv -> https://www.sphinx-doc.org/en/master/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 9 added, 1 changed, 0 removed
/home/tkloczko/rpmbuild/BUILD/default_values-0.6.0/doc-source/docs.rst:5: ERROR: Unknown directive type "autosummary-widths".

.. autosummary-widths:: 1/2
    :html: 7/20 [docutils]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.default_regex' with 'default_regex'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.no_default_regex' with 'no_default_regex'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.format_default_value' with 'format_default_value'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.get_arguments' with 'get_arguments'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.get_class_defaults' with 'get_class_defaults'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.get_function_defaults' with 'get_function_defaults'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.process_default_format' with 'process_default_format'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.process_docstring' with 'process_docstring'. [autosummary.import_cycle]
WARNING: Summarised items should not include the current module. Replace 'sphinxcontrib.default_values.setup' with 'setup'. [autosummary.import_cycle]
/home/tkloczko/rpmbuild/BUILD/default_values-0.6.0/doc-source/index.rst:176: ERROR: Unknown interpreted text role "rst:field". [docutils]
/home/tkloczko/rpmbuild/BUILD/default_values-0.6.0/doc-source/index.rst:176: ERROR: Unknown interpreted text role "rst:field". [docutils]

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 514, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 381, in build
    self.builder.build_update()
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 355, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 385, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 502, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 567, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 630, in read_doc
    publisher.publish()
  File "/usr/lib/python3.10/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.10/site-packages/sphinx/io.py", line 106, in read
    self.parse()
  File "/usr/lib/python3.10/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/tkloczko/rpmbuild/BUILD/default_values-0.6.0/./sphinxcontrib/default_values/__init__.py", line 345, in parse
    super().parse(inputstring, document)
  File "/usr/lib/python3.10/site-packages/sphinx/parsers.py", line 85, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 3034, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2359, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2384, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2662, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2106, in directive
    return self.run_directive(
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2156, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.10/site-packages/sphinx_licenseinfo/__init__.py", line 100, in run
    distro = get_distribution(self.options["py"])
  File "/usr/lib/python3.10/site-packages/dist_meta/distributions.py", line 591, in get_distribution
    raise DistributionNotFoundError(name)
dist_meta.distributions.DistributionNotFoundError: default_values

Exception occurred:
  File "/usr/lib/python3.10/site-packages/dist_meta/distributions.py", line 591, in get_distribution
    raise DistributionNotFoundError(name)
dist_meta.distributions.DistributionNotFoundError: default_values
The full traceback has been saved in /tmp/sphinx-err-nfwd97ac.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by kloczek** [comment]
Closing.
it was missing `extras-require` module.
